### PR TITLE
Added CSS module file

### PR DESCRIPTION
**Pull request by VadimDmitr**

### CODE REVIEW

**Comment by VadimDmitr** [comment]
Added the possibility for creating/writing data to AirTable from my app and Added a CSS module file.

**Comment by Asel-K** [comment]
Styling looks amazing! Great job.

**Comment by Asel-K** [comment]
I'd also recommend to check the browser if there are any warnings or errors thrown (It's a good idea to keep the browser's development tools open so that you see the errors/warnings that React prints out) I believe no errors/warnings will be one of the requirements for your finals. And make sure that the lists are displayed/rendered properly. Once again great job overall!

**Comment by VadimDmitr** [comment]
Thank you Asel for your time and advice!
Have a great weekend!

Sincerely,
Vadim D.

**Pull request merged**
